### ISSUE TITLE
やっぱ本体が起動できません

### ISSUE THREAD

**Issue by bltimer** [SKN-JP/Road_of_Gold#28]
🛑 Application terminated due to an exception. Exception code: EXCEPTION_ACCESS_VIOLATION
赤字で上記エラーが出ます

マップエディタのほうは起動できてるのですが何か特別なランタイムの導入とが必要なのでしょうか？[

**Comment by sknjpn** [comment]
報告ありがとうございます。

どうやらシステムのバグの可能性が高いです。
一定の確率でこちらでも確認しているので、
本体の再起動を繰り返せばエラーを回避できるかもしれません。
マップエディタが起動出来ているならランタイムの導入などは必要ありません。

自作マップを使っている場合は、
Map/自作マップの名前/urbans.json
を開いて、
"NumCitizens": 市民の人数
の数値が1000以下であることを確認してください。
市民が異常に多いと起動できない場合があります。

新しいバージョンに更新しているので、そちらでも試してみてください。
それでもダメそうなら、またご連絡してもらえたら幸いです。

**Comment by hirmiura** [comment]
バージョンが分からないのであくまで予想になります。

masterブランチの最新版を自前でコンパイルしたものであれば、Route.cppの[35行目](https://github.com/SKN-JP/Road_of_Gold/blob/7b720b3dc1eda2052533147696b9cb82f801df7a/Road_of_Gold/Route.cpp#L35)と[112行目](https://github.com/SKN-JP/Road_of_Gold/blob/7b720b3dc1eda2052533147696b9cb82f801df7a/Road_of_Gold/Route.cpp#L112)の変数宣言が間違っています。&が要りません。
`auto& n1 = temp[i];` ➡️ `auto n1 = temp[i];`

これで起動時のACCESS_VIOLATIONは消えます。

**Comment by sknjpn** [comment]
こちらでも調べましたが、恐らくそれが原因のようです。
情報提供ありがとうございます。

現在Road of Goldは開発が終了しRoad of Gold 2に移行しているので、
そちらの方でしたらそのバグは起こらないと思います。
