### ISSUE TITLE
ドット絵作ってみました。

### ISSUE THREAD

**Issue by 66588257** [SKN-JP/Road_of_Gold#29]
ドット絵作ってみました。
[](https://box.yahoo.co.jp/guest/viewer?sid=box-l-6txy3xdawqbwxxeal6kvpdg2wi-1001&uniqid=f339f308-d54f-4d2c-be7a-fe4d8f25ed0f&viewtype=detail)
拙い絵ですがつなぎとしてでも使って頂けると嬉しいです。

**Comment by sknjpn** [comment]
ありがとうございます。

そのドット絵はどこに上げられているのでしょうか？

URLを貼っていただけると嬉しいです。

**Comment by 66588257** [comment]
間違えて空の文字列に貼ってしまったようです。
[こちら](https://box.yahoo.co.jp/guest/viewer?sid=box-l-6txy3xdawqbwxxeal6kvpdg2wi-1001&uniqid=f339f308-d54f-4d2c-be7a-fe4d8f25ed0f&viewtype=detail)

**Comment by sknjpn** [comment]
確認できましたので、次回のアップデートから適用させて頂きます。

**Comment by 66588257** [comment]
ありがとうございます！
次回の更新も楽しみにして待ってます！
