### ISSUE TITLE
マップエディタについて

### ISSUE THREAD

**Issue by kotenman** [SKN-JP/Road_of_Gold#31]
マップエディタでオリジナルマップを作ってみたのですがゲーム・プラネットビューワーに反映されません
マップフォルダに最初から入ってるBatailleフォルダを消し、自作マップフォルダのみにするとゲームが起動しなくなります
オリジナルマップの適用方法を教えて下さい

**Comment by sknjpn** [comment]
該当マップファイル内のMap/Urbans.jsonファイルに問題がある可能性があります。

都市配置を一つも行っていない場合、初期交易ユニットの配置に失敗しエラーを起こします。
新規に都市を配置するか、Bataille/Urbans.jsonファイルをコピーしてください。

ただし、PlanetViewerはUrbans.jsonファイルに依存しないため、問題なく起動できると思います。

Mapファイルに複数マップがある場合、名前の順で読み込まれます。

**Comment by kotenman** [comment]
再度新しく地形を生成して他の地図ファイルを消したところ、おっしゃる通りプラネットビューワーでの地図読み込みは出来ました
前回作ったマップはマップエディタでも登録した都市が確認できなかった（Urbans.jsonには書き込まれてる）為、Urbans.jsonファイルに問題があったのだと思います

新しく作ったマップはroad_of_goldでの読み込みは出来ましたが、幾ら待っても（時間経過速度は50%以上）商隊が都市から出てこないので
人口と交易品の生産量がかなり多め（人口・交易品共1000以下）の都市を一つ追加したところまた起動しなくなってしまいました

あと都市登録の数値入力ウィンドウで１文字目に８と９（800等の数値）が入力出来ないのはバグでしょうか？
いま自分が使っているキーボードはかなり調子が悪いので環境依存のような気もするんですが教えていただけたら嬉しいです

**Comment by sknjpn** [comment]
最近のアップデートで労働者の生産には農地が必要になりました。
農地がなければお金の生産が行われないため、大変不安定になります。（この場合の動作は現状保証されません）
農地は最低でも1あれば大丈夫です。
交易ユニットの行動条件に「商品生産が行われていること」があるため、追加で香辛料やコーヒーなど何らかの資源が必要です。
また、陸路または海路が存在している必要があります。別の大陸の内陸同士では接続されません。
あと、マップデータを圧縮してアップローダーに上げてもらえれば原因を調査しますので、そうしてもらえたら嬉しいです。（この場合、Map/ファイル内のみで大丈夫です）

動画は上げていませんが、動作を改善したバージョンに更新したので、再ダウンロードしてみてください。

数値入力に関してはバグです。ただし、すぐには修正できないので、urbans.jsonファイルから直接編集するのが手軽です。

**Comment by kotenman** [comment]
https://www.axfc.net/u/3842323.zip
起動できないマップ（フォルダ名：マダ途中）・交易ユニットが出てこないマップ（フォルダ名：新都市）を上げています
起動できないマップはurbans.jsonファイルが書き換わっても起動出来ません

新しいデータに付いているマップエディタですが、前半角キーを押すとウィンドウ化されて止まってしまいます

**Comment by sknjpn** [comment]
「マダ途中」→Urbans.jsonファイル内のProductivityの数値に「nan」が存在することが原因です。
1.0にすることをお勧めします。（整数を代入した場合、強制的に1.0になります）
また、非常に小さい数値になっているものがあるので、修正しておくことをお勧めします。

「新都市」→解析したところ、惑星内に交易路が引けない都市が１つでも存在すると交易路が事実上引けない状態になることが分かりました。
具体的には
・ダマスカス→陸路はあるが、幌馬車の航続距離6000mtよりも長いため、引けない
・コルドバ→内陸であり、海路は引けず、陸路で接続できる都市がない
となっています。
これを解決するには「比較的近いところに」「海路または陸路で接続できるようにする」必要があります。

ウィンドウ化についてはこちらでも確認できました。報告ありがとうございます。
