### ISSUE TITLE
Lua搭載RoG起動失敗　（ニコニココメント報告）

### ISSUE THREAD

**Issue by coil424** [SKN-JP/Road_of_Gold#37]
開発者様連日の更新お疲れ様です。

今回、進捗報告29にて本体の起動失敗についての詳細を報告いたします。

当方の性能（簡易）
Windows10Home64bit ver.1703 ビルド15063.608
Inter Core i7-7700
RAM 16G (DDR4)
GTX1050Ti

となります。

起動失敗のスクリーンショットを添付します。

![rogx64](https://user-images.githubusercontent.com/32209434/30809217-04b3eec8-a23c-11e7-88ec-f80bb864ff75.png)

![rogx86](https://user-images.githubusercontent.com/32209434/30809221-0736ba86-a23c-11e7-888d-2e95e65d9245.png)

こちらのシステム等の不足でありましたら対応しますので確認をお願いします。

**Comment by sknjpn** [comment]
報告ありがとうございます。

問題を修正したバージョンをアップロードしておきました。

**Comment by coil424** [comment]
ありがとうございます。　機能追加で思ついたことなどあれば書き込みます
