### ISSUE TITLE
ある地点を横断するような航路を取る時、ワープするようなルートが設定されます

### ISSUE THREAD

**Issue by TEN11111** [SKN-JP/Road_of_Gold#39]
はじめまして。

前からなのですが、ある経度をまたぐような航路または陸路を取る時、反対方向に惑星を一周する（海や陸地を無視して）一直線のルートが設定され、実際の船団はそれに沿ってワープするような動きをします。また、最新版でそのような船団をまとめて選択するとプログラムが落ちます。

![default](https://user-images.githubusercontent.com/32391772/31017517-b94910e6-a563-11e7-975a-a3a5fa0ce03b.png)

実際の見た目はアップした画像の通りなのですが、既知の問題でしょうか。それとも開発元の環境では発生しない問題でしょうか。

**Comment by sknjpn** [comment]
報告ありがとうございます。

ワープする問題については確認できましたので、次回のアップデートで修正しておきます。

ただし、船団選択時のクラッシュについては確認できなかったので、
クラッシュする条件を詳しく教えて頂けると嬉しいです。

**Comment by TEN11111** [comment]
お疲れ様です。すみません、クラッシュの精密な条件は絞り切れていません。
100個くらいの船団が行き来してるところで「がばっと」まとめて選択するとクラッシュする感じです。2，3個の船団を選択する程度なら落ちないです。

分かっている所ではゲーム速度は発生条件には影響しないみたいです。また、同じ操作をしても少なくても初期マップにあるボヘミアでは（重くはなるものの）落ちないです。

**Comment by TEN11111** [comment]
今気づきましたが、一点明確な点があって、
都市A⇒都市Bに行く船団と、都市A⇒都市Cに行く船団をまとめて選択すると数に関係なく落ちるみたいです。逆に都市A⇒都市Bに行く船団だけを選択するようにすれば、大量に選択しても落ちません。少なくてもワープするマップではそうです。前レスに書いた通り、ボヘミアでは発生しません。

**Comment by sknjpn** [comment]
どうやら都市にいるユニットを選択することが原因のようです。
（都市待機中のユニットの状態取得に失敗するため）
ボヘミアマップでも同様の問題が発生します。

開発版では修正されていますが配布には時間がかかるため、
それまでは都市を含めずに選択することで対応してください。

もし、都市内ユニット選択をしなくても発生する場合は別の原因が考えられますので、
再度ご連絡ください。

**Comment by sknjpn** [comment]
あと、具体的な原因ですが、
１、商会AIはユニットに交易路を指示する際に一旦プログラムをリセットする
２、商会AIがユニットに最適な交易路を検索する
３、もし最適な交易路が存在しない場合、プログラムは空のままになる
４、プログラムが空の場合に選択されたユニット情報を表示しようとしてクラッシュする

この場合、ゲーム開始時はすべてのユニットのプログラムが空なので、
時間を進めずにユニット選択すると必ず落ちるようです。

陸路が１つもない場合、陸上ユニットの交易路は存在しなくなるので、この場合も選択すると落ちます
（そのマップでは陸路がなかったのかもしれません）

**Comment by TEN11111** [comment]
すみません、誤情報でしたね。

確かにおっしゃる通りで、陸上交易ルートは存在しないマップでした。
対応ありがとうございます。
