### ISSUE TITLE
x64版が更新されていない

### ISSUE THREAD

**Issue by ghost** [SKN-JP/Road_of_Gold#42]
x64版をダウンロードすると
version.txtは更新されているみたいですが、exeが更新されていないようです。

**Comment by coil424** [comment]
管理者ではありませんが失礼します。
ニコニコ動画の方には 32 bit 版のみ更新 と記載されていましたが そちらのバージョンではないですか？

**Comment by ghost** [comment]
なるほど、そうだったんですね。
よく見ていませんでした。
Closeしておきます。
