### ISSUE TITLE
市場システムについての案

### ISSUE THREAD

**Issue by sknjpn** [SKN-JP/Road_of_Gold#44]
現状では各商会が自由に価格を設定できるが、「市場」が価格を掲示するシステム
「市場」は価格を「市民の収入関数」と総商品数より算出し、その日の価格を決定する
商会は「市場」が一定以下の価格を掲示した際に販売を停止することができる
このシステムにより、同じ商品ならば同じ価格になるため、商品棚の処理を大幅に削減できる
「市場」による強制的なコントロールが可能になるため、プレイヤーによる工作対策ができる

**Comment by coil424** [comment]
例としてなんですが都市入れは

E1_23時59分 市場入荷締切 集計
E2_00時00分 市場価格公示 入荷開始（翌日販売分）
E3_08時00分 市民取引（E1で締切した分）
E4_23時59分 市場入荷締切 集計
以下繰り返し

となるのでしょうか？

**Comment by coil424** [comment]
上記例 時間は適当です。

また、商人が市場から物資を仕入れる場合はどのような感じになるのでしょうか？

**Comment by sknjpn** [comment]
多分、予定されているものだと、

0時0分にその全ての処理を実行する形になります。
市場はその時に取引価格を全入荷量から「市民の価格と消費量の関係式」を用いて算出します。

取引価格が掲示されるとまず、販売側が取引価格が妥当か判定し、出品を決めます。
例えば、仕入れが1000Gなのに、取引価格が830Gだとすると赤字になるから販売しない、といった感じですね

次に購入側が取引価格が妥当か判定し、購入を決めます。
もし、高すぎると感じたら購入をしない判断ができます。

**Comment by sknjpn** [comment]
商会が市場から仕入れる場合、以前と同様に購入代理人を都市に配置し、定期購入をする方式にしようと考えています。（例えば、30日に一回600個購入するのを1日に20個購入するようにします）
そして、購入代理人には購入価格を設定させ、市場が設定した取引価格が高すぎる場合は購入させないように考えています。
