### ISSUE TITLE
川について

### ISSUE THREAD

**Issue by TEN11111** [SKN-JP/Road_of_Gold#47]
更新お疲れ様です。
大した事ではないのですが、マップエディタで川を引く際に海上で実行すると海に川が引けるのですがこれは仕様でしょうか？
個人的にはちょっと違和感がある挙動なので質問です。

**Comment by sknjpn** [comment]
仕様です。

川はノード（小さなバイオームの欠片）とノードを接続する経路を海として認識させるシステムです。
そのため、バイオームの種類は問われず、海バイオーム同士であっても問題なく動作します。

また、川を設置した後から陸地バイオームを海バイオームを変更できるのですが、
そのたびに川を削除した場合、マップ製作者がもう一度引き直す必要があり、マップ製作者のストレスにつながると考えています。

現状、川のシステムは無理のある実装をしていて、今後バグの温床になると考えています。
なので、他の機能に比べて単純な設計をしています。

**Comment by TEN11111** [comment]
了解しました。ご返答ありがとうございます。
