### ISSUE TITLE
バイオーム生成、マップシステムについて

### ISSUE THREAD

**Issue by sknjpn** [SKN-JP/Road_of_Gold#49]
現行のNode数を30000から1000～10000まで削減し、ルートのカクカクを減らす
代わりにボロノイ図に依存していたマップ描画から、自由な画像のマップへ移行する

問題
・ピクセル単位のマップ変更はマップ製作の難易度を高めるため、ペイント機能を強化する必要がある。
・沿岸部の都市は正確設置が困難になるため、むしろノードを自分で設定できるようにするべき？
ノードを自分で設定するならば非常に柔軟な設定が可能になる

**Comment by sknjpn** [comment]
![mapeditor 2017_10_16 17_54_59](https://user-images.githubusercontent.com/29691164/31603451-3399a2c2-b29b-11e7-9f6c-d5111baada3a.png)

Node数を1000にして出力したもの

**Comment by sknjpn** [comment]
![99 2017_10_16 18_07_31](https://user-images.githubusercontent.com/29691164/31604009-ed4d02b2-b29c-11e7-992a-4b6cd03e4b68.png)
![99 2017_10_16 18_07_43](https://user-images.githubusercontent.com/29691164/31604011-ed8dd5f8-b29c-11e7-9894-8e916de51f46.png)
![99 2017_10_16 18_07_23](https://user-images.githubusercontent.com/29691164/31604019-fa9b9d84-b29c-11e7-8681-24120e5d1210.png)

ピクセル単位のバイオームに変更したが、誤魔化しができないせいでバイオームがひどくなった。

**Comment by coil424** [comment]
ルートの角々という言うのはMAP上で動く輸送実体が角々するのが気になるということでしょうか？

逆にNode数を増やすのはどうでしょう。でも処理タイムにダイレクトに響きますかね・・・。

**Comment by sknjpn** [comment]
そういうことですね。
現状は別のゲームで試しているベジェ曲線を利用することで対応を考えていますが、描画コストの問題が未知数です

Node数は増やしても極限的にはへクスマップになるだけでカクカクは改善されません。
ですが、遠目で見た時のルートの見た目は改善されるので、
現行の40,000Nodeから50,000Nodeに増量し、さらに精度も向上させる予定です。

処理速度に関しては描画時のみの問題なので、オプションで切り替え可能にすることも考えています
