### ISSUE TITLE
test

### ISSUE THREAD

**Issue by sknjpn** [SKN-JP/Road_of_Gold#9]
ここで質問や、バグ報告、今後の要望などを受け付けています。  
  
投稿してもらえれば製作者本人が回答します。  
  
気軽に投稿してください。

**Comment by kis-sako** [comment]
遊んでみました　面白かったです

実際にやってみて気になった点ですが
初め、何をすればいいか分からず少し戸惑いました
操作方法などのreadme.txtをざっとでも書いて頂けると始めるのが楽になるかと思います
それと都市を作るとき、一つ一つ数値を設定するのがかなり面倒に感じました
周囲の環境から自動で設定する初期数値を決定する機能があれば
バンバン都市を作ってあとは好みに細かく数値を変更できて楽かなと思いました

素人の一意見ですが参考程度に考えていただけたら幸いです
毎回更新楽しみにしてます

**Comment by sknjpn** [comment]
テスト

**Comment by sknjpn** [comment]
テスト２
